import type { CollectionConfig } from 'payload'
import { authenticated, staffOnly } from '../access/communityAccess'

export const CommunityReports: CollectionConfig = {
  slug: 'community-reports',
  labels: {
    singular: 'Community Report',
    plural: 'Community Reports',
  },
  admin: {
    useAsTitle: 'reason',
    defaultColumns: ['reportType', 'reason', 'status', 'priority', 'createdAt'],
    group: 'Community',
  },
  access: {
    create: authenticated,
    read: staffOnly,
    update: staffOnly,
    delete: staffOnly,
  },
  timestamps: true,
  fields: [
    {
      name: 'reportType',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Comment', value: 'comment' },
        { label: 'Chat Message', value: 'chat_message' },
        { label: 'Chat Channel', value: 'chat_channel' },
        { label: 'User Profile', value: 'user_profile' },
        { label: 'Creator Content', value: 'creator_content' },
        { label: 'Other', value: 'other' },
      ],
    },
    {
      name: 'reporter',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      index: true,
    },
    {
      name: 'reportedUser',
      type: 'relationship',
      relationTo: 'users',
      index: true,
    },
    {
      name: 'comment',
      type: 'relationship',
      relationTo: 'comments',
      index: true,
    },
    {
      name: 'chatMessage',
      type: 'relationship',
      relationTo: 'chat-messages',
      index: true,
    },
    {
      name: 'chatChannel',
      type: 'relationship',
      relationTo: 'chat-channels',
      index: true,
    },
    {
      name: 'targetCollection',
      type: 'text',
      admin: {
        description: 'Optional fallback for reporting any collection not directly linked above.',
      },
    },
    {
      name: 'targetDocumentId',
      type: 'text',
    },
    {
      name: 'reason',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Spam', value: 'spam' },
        { label: 'Harassment or Bullying', value: 'harassment' },
        { label: 'Threat or Violence', value: 'threat_violence' },
        { label: 'Hate Speech', value: 'hate_speech' },
        { label: 'Misinformation', value: 'misinformation' },
        { label: 'Private Information / Doxxing', value: 'private_information' },
        { label: 'Graphic or Explicit Content', value: 'graphic_explicit' },
        { label: 'Solicitation or Scam', value: 'solicitation_scam' },
        { label: 'Copyright or Plagiarism', value: 'copyright_plagiarism' },
        { label: 'Impersonation', value: 'impersonation' },
        { label: 'Off-Topic Flooding', value: 'off_topic_flooding' },
        { label: 'Brand Safety Concern', value: 'brand_safety' },
        { label: 'Other', value: 'other' },
      ],
    },
    {
      name: 'details',
      type: 'textarea',
      required: true,
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'open',
      index: true,
      options: [
        { label: 'Open', value: 'open' },
        { label: 'In Review', value: 'in_review' },
        { label: 'Action Taken', value: 'action_taken' },
        { label: 'Dismissed', value: 'dismissed' },
        { label: 'Escalated', value: 'escalated' },
        { label: 'Closed', value: 'closed' },
      ],
    },
    {
      name: 'priority',
      type: 'select',
      required: true,
      defaultValue: 'normal',
      index: true,
      options: [
        { label: 'Low', value: 'low' },
        { label: 'Normal', value: 'normal' },
        { label: 'High', value: 'high' },
        { label: 'Urgent', value: 'urgent' },
        { label: 'Legal / Safety Risk', value: 'legal_safety_risk' },
      ],
    },
    {
      name: 'assignedTo',
      type: 'relationship',
      relationTo: 'users',
      index: true,
    },
    {
      name: 'reviewedBy',
      type: 'relationship',
      relationTo: 'users',
    },
    {
      name: 'reviewedAt',
      type: 'date',
    },
    {
      name: 'actionTaken',
      type: 'select',
      defaultValue: 'none',
      options: [
        { label: 'None', value: 'none' },
        { label: 'Content Hidden', value: 'content_hidden' },
        { label: 'Content Removed', value: 'content_removed' },
        { label: 'User Warned', value: 'user_warned' },
        { label: 'User Muted', value: 'user_muted' },
        { label: 'User Banned', value: 'user_banned' },
        { label: 'Thread Locked', value: 'thread_locked' },
        { label: 'Escalated to Editorial', value: 'escalated_editorial' },
        { label: 'Escalated to Legal', value: 'escalated_legal' },
        { label: 'Dismissed', value: 'dismissed' },
      ],
    },
    {
      name: 'resolutionNotes',
      type: 'textarea',
    },
  ],
}
